# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 1
  end

  config.vm.network :private_network, type: :dhcp # Create local private network
  config.vm.network :forwarded_port, guest: 80, host: 4800 # Varnish

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../../ansible/local_loadbalancer.yml"
    ansible.ask_vault_pass = true
  end

end
