---
- name: add java repo
  apt_repository: repo='ppa:webupd8team/java' state=present

- name: update apt
  apt: update_cache=yes

- name: Automatically select the Oracle License
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections

- name: install oracle-java7
  apt: pkg=oracle-java7-installer state=latest update-cache=yes force=yes
