# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    config.vm.box = "lcn/debian-wheezy-64"
    config.vm.hostname = "dk-dev"

    config.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
    end

    config.vm.network :private_network, ip: "192.168.16.16"
#    config.vm.network :forwarded_port, guest: 8080, host: 8080 # Tomcat Server
    config.vm.network :forwarded_port, guest: 3306, host: 3306 # MySQL
    config.vm.network :forwarded_port, guest: 9200, host: 9200 # Elastic Search
    config.vm.network :forwarded_port, guest: 9300, host: 9300 # Elastic Search
#    config.vm.network :forwarded_port, guest: 15672, host: 15000 # RabbitMQ Management Console
#    config.vm.network :forwarded_port, guest: 5672, host: 5672 # RabbitMQ amqp primary
#    config.vm.network :forwarded_port, guest: 5673, host: 5673 # RabbitMQ amqp secondary
    config.vm.network :forwarded_port, guest: 6379, host: 6379 # Redis

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "../ansible/local_webapp.yml"
        ansible.extra_vars = "../ansible/local_extra_vars.yml"
    end

end
