---
# file: roles/elasticsearch/tasks/main.yml
- name: ensure python-software-properties is installed
  apt: pkg=python-software-properties state=installed

- name: add elasticsearch public key
  apt_key: url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present

- name: add elasticsearch official apt repository
  apt_repository: repo='deb http://packages.elasticsearch.org/elasticsearch/1.4/debian stable main' state=present

- name: update apt
  apt: update_cache=yes

- name: install elasticsearch
  apt: pkg=elasticsearch state=installed force=yes

- name: add elasticsearch process to startup script
  command: update-rc.d elasticsearch defaults 95 10
  sudo: yes
  sudo_user: root

- name: copy ES config file
  template: src=elasticsearch.yml dest=/etc/elasticsearch/elasticsearch.yml owner=root group=root mode=0644

- name: restart elasticsearch
  service: name=elasticsearch state=restarted

- name: Install ES Head
  command: /usr/share/elasticsearch/bin/plugin -install mobz/elasticsearch-head

- name: Install ES Paramedic
  command: /usr/share/elasticsearch/bin/plugin -install karmi/elasticsearch-paramedic

- name: Install ES BigDesk
  command: /usr/share/elasticsearch/bin/plugin -install lukas-vlcek/bigdesk

- name: Install ES Inqusitor
  command: /usr/share/elasticsearch/bin/plugin -install polyfractal/elasticsearch-inquisitor